/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DPixInterface extends ethers.utils.Interface {
  functions: {
    "buyNFT(uint256)": FunctionFragment;
    "dpixNFT()": FunctionFragment;
    "dpixToken()": FunctionFragment;
    "name()": FunctionFragment;
    "price(uint256)": FunctionFragment;
    "setPrice(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buyNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dpixNFT", values?: undefined): string;
  encodeFunctionData(functionFragment: "dpixToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "price", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dpixNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dpixToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "price", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;

  events: {};
}

export class DPix extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DPixInterface;

  functions: {
    buyNFT(
      _id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "buyNFT(uint256)"(
      _id: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    dpixNFT(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "dpixNFT()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    dpixToken(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "dpixToken()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    name(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "name()"(
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    price(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "price(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    setPrice(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setPrice(uint256,uint256)"(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  buyNFT(
    _id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "buyNFT(uint256)"(
    _id: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  dpixNFT(overrides?: CallOverrides): Promise<string>;

  "dpixNFT()"(overrides?: CallOverrides): Promise<string>;

  dpixToken(overrides?: CallOverrides): Promise<string>;

  "dpixToken()"(overrides?: CallOverrides): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  price(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "price(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setPrice(
    _id: BigNumberish,
    _price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setPrice(uint256,uint256)"(
    _id: BigNumberish,
    _price: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    buyNFT(_id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "buyNFT(uint256)"(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    dpixNFT(overrides?: CallOverrides): Promise<string>;

    "dpixNFT()"(overrides?: CallOverrides): Promise<string>;

    dpixToken(overrides?: CallOverrides): Promise<string>;

    "dpixToken()"(overrides?: CallOverrides): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    price(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "price(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPrice(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPrice(uint256,uint256)"(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    buyNFT(_id: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "buyNFT(uint256)"(
      _id: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    dpixNFT(overrides?: CallOverrides): Promise<BigNumber>;

    "dpixNFT()"(overrides?: CallOverrides): Promise<BigNumber>;

    dpixToken(overrides?: CallOverrides): Promise<BigNumber>;

    "dpixToken()"(overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    price(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "price(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setPrice(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setPrice(uint256,uint256)"(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyNFT(
      _id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "buyNFT(uint256)"(
      _id: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    dpixNFT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "dpixNFT()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    dpixToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "dpixToken()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    price(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "price(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPrice(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setPrice(uint256,uint256)"(
      _id: BigNumberish,
      _price: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
